### PR TITLE
Gauss-Legendre Fixes

### LINKED ISSUE #40: Hardcoded tolerance in Gauss-Legendre
The Gauss-Legendre quadrature routine hardcodes an absolute tolerance `eps = 3.0e-11`. The origin of this value is not documented, and it also seems a bit too large to me. Since $x\in[-1,1]$, `eps` should be of the order of machine epsilon **of the employed data type**.

Another thing that needs to be fixed is to employ a `for` loop instead of the current `while` loop which risks hanging. Instead, one should take e.g. a maximum of 100 Newton iterations, and then throw an error if convergence was not achieved.

### PR DESCRIPTION
**Pull request by wavefunction91**
1. Tightens convergence tolerance (1e-11 -> epsilon) for Gauss-Legendre Newton iterations 
2. Makes GL iterations of fixed range to avoid infinite loops
3. Moves to structured bindings for `eval_Pn` return

Closes #40.

### CODE REVIEW

**Comment by wavefunction91** [comment]
@susilehtola Have a look

File: include/integratorxx/quadratures/gausslegendre.hpp [hunk 1]
```diff
@@ -96,17 +96,29 @@ struct quadrature_traits<
...
         // Solve the root to eps absolute precision
-        while(std::abs(z-z_old) > eps) {
+        bool converged = false;
+        const int maxit = 100;
+        for(int it = 0; it < maxit; ++it) {
           // Evaluate the Legendre polynomial at z and its derivative
-          auto pn_eval = eval_Pn(z,npts);
-          p_n = pn_eval.first;
-          dp_n = pn_eval.second;
+          std::tie(p_n, dp_n) = eval_Pn(z,npts);
```
Comment (susilehtola) [inline include/integratorxx/quadratures/gausslegendre.hpp:103]: Oh cool, so a more compact syntax is possible

File: include/integratorxx/quadratures/gausslegendre.hpp [hunk 2]
```diff
@@ -96,17 +96,29 @@ struct quadrature_traits<
...
 
           // Newton update for root
           z_old = z;
           z  = z_old - p_n / dp_n;
```
Comment (susilehtola) [inline include/integratorxx/quadratures/gausslegendre.hpp:107]:
```suggestion
          z  -= p_n / dp_n;
```

Comment (wavefunction91) [reply include/integratorxx/quadratures/gausslegendre.hpp:107]: Does `z` always contain what was previously in `z_old`? Working from mobile, so it's hard to tell.

Comment (susilehtola) [reply include/integratorxx/quadratures/gausslegendre.hpp:107]: Yes, `z_old` is set to `z_old=z` on the preceding line.
